title: <center>Sem Leontev</center> # your name (or website title) here
logo: "/images/profile1.png?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br><br>
  Hi there. My name is Sem and I am an experienced Data Scientist with 9 years of expertise in Data Analysis, 
  Machine Learning and AI. I am Proficient in Python, R and SQL. Holds a Master's degree in Business Analytics from the
  University of California, Irvine.
  <br><br>
  <a href="https://www.linkedin.com/in/semleontev/">LinkedIn</a> <br>
  <a href="https://github.com/seemyon">GitHub</a> <br>
  <a href="/pdf/sem_leontev_resume.pdf">Resume</a> <br>


theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
