title: Sem Leontev # your name (or website title) here
logo: "/images/profile1.png?raw=false" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Data Scientist with 9+ years of experience in implementing statistical 
  modeling and machine learning techniques. Skilled in Python, R, SQL, Tableau, Excel, and Big Data technologies.
  <br><br>
  <a href="https://www.linkedin.com/in/semleontev/">Let's connect on LinkedIn</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
